import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const bundlePath = path.join(__dirname, '..', 'src', 'solver-bundle.ts');
const YT_SOLVER_URL = 'https://github.com/yt-dlp/ejs/releases/latest/download/yt.solver.core.js';

try {
    const splitToken = 'var jsc = (function (meriyah, astring) {';
    
    console.log(`Downloading latest solver from ${YT_SOLVER_URL}...`);
    const response = await fetch(YT_SOLVER_URL);
    if (!response.ok) {
        throw new Error(`Failed to download solver: ${response.status} ${response.statusText}`);
    }
    const newYtSolver = await response.text();

    const ytParts = newYtSolver.split(splitToken);
    if (ytParts.length < 2) {
        throw new Error('Could not find the start of jsc function in yt.solver.core.js');
    }

    const header = `// @ts-nocheck
/*!
 * SPDX-License-Identifier: Unlicense
 * This file was automatically generated by https://github.com/yt-dlp/ejs
 *
 * Modified for untube: Native Node.js npm dependencies are used instead of bundled minified code.
 */
import * as meriyah from 'meriyah';
import * as astring from 'astring';

`;

    let newBundle = header + splitToken + ytParts.slice(1).join(splitToken) + '\n\nexport default jsc;\n';
    
    // Apply the fix: ignore async functions when extracting solvers to prevent crash with cookies
    newBundle = newBundle.replace(
        /if\s*\(\s*node\.type\s*===\s*(['"])FunctionDeclaration\1\s*\)\s*\{/,
        "if (node.type === 'FunctionDeclaration') {\n      if (node.async) {\n        return null;\n      }"
    );
    newBundle = newBundle.replace(
        /if\s*\(\s*node\.expression\.type\s*!==\s*(['"])AssignmentExpression\1\s*\)\s*\{\s*return\s+null\s*;\s*\}/,
        "if (node.expression.type !== 'AssignmentExpression') {\n        return null;\n      }\n      if (node.expression.right && node.expression.right.async) {\n        return null;\n      }"
    );
    newBundle = newBundle.replace(
        /for\s*\(\s*const\s+declaration\s+of\s+node\.declarations\s*\)\s*\{/,
        "for (const declaration of node.declarations) {\n        if (declaration.init && declaration.init.async) {\n          continue;\n        }"
    );
    
    fs.writeFileSync(bundlePath, newBundle, 'utf8');
    console.log('Successfully updated src/solver-bundle.ts with the latest yt.solver.core.js from GitHub releases!');
} catch (err) {
    console.error('Failed to update solver:', err);
    process.exit(1);
}
