import fs from 'fs';
import { CookieJar, Cookie } from 'tough-cookie';

export class RawCookie {
    constructor(
        public onRead: () => string | Promise<string>,
        public onWrite: (cookie: string) => void | Promise<void>
    ) {}
}

class CookieManager {
    private source: string | RawCookie | undefined;
    public jar: CookieJar;

    constructor(source?: string | RawCookie) {
        this.source = source;
        this.jar = new CookieJar(undefined, { looseMode: true });
    }

    async load(): Promise<void> {
        if (!this.source) return;

        let content = '';
        if (this.source instanceof RawCookie) {
            content = await this.source.onRead();
        } else if (typeof this.source === 'string') {
            if (fs.existsSync(this.source)) {
                content = fs.readFileSync(this.source, 'utf8');
            }
        }

        if (!content) return;

        const lines = content.split('\n');
        for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed || (trimmed.startsWith('#') && !trimmed.startsWith('#HttpOnly_'))) continue;
            
            let isHttpOnly = false;
            let actualLine = trimmed;
            if (actualLine.startsWith('#HttpOnly_')) {
                isHttpOnly = true;
                actualLine = actualLine.substring(10);
            }
            
            const parts = actualLine.split('\t');
            if (parts.length < 7) continue;
            
            const domain = parts[0];
            const includesSubdomains = parts[1] === 'TRUE';
            const path = parts[2];
            const secure = parts[3] === 'TRUE';
            const expires = parseInt(parts[4]!, 10);
            const name = parts[5];
            const value = parts[6];
            
            const cookie = new Cookie({
                key: name,
                value: value,
                domain: domain?.startsWith('.') ? domain.substring(1) : domain,
                path: path,
                secure: secure,
                httpOnly: isHttpOnly,
                hostOnly: !includesSubdomains,
                expires: expires <= 0 ? 'Infinity' : new Date(expires * 1000)
            });
            
            const protocol = secure ? 'https' : 'http';
            const domainProp = cookie.domain || 'youtube.com';
            const host = domainProp.startsWith('.') ? domainProp.substring(1) : domainProp;
            const url = `${protocol}://${host}${path}`;
            
            try {
                this.jar.setCookieSync(cookie, url, { ignoreError: true });
            } catch (e) {
            }
        }
    }

    async save(): Promise<void> {
        let out = '# Netscape HTTP Cookie File\n';
        out += '# This file was generated by Node.js\n\n';
        
        const allCookies = await new Promise<Cookie[]>((resolve, reject) => {
            this.jar.store.getAllCookies((err, cookies) => {
                if (err) reject(err);
                else resolve(cookies || []);
            });
        });

        for (const cookie of allCookies) {
            let prefix = cookie.httpOnly ? '#HttpOnly_' : '';
            let domain = cookie.domain || '';
            if (!cookie.hostOnly && !domain.startsWith('.')) domain = '.' + domain;
            const includeSubdomains = domain.startsWith('.') || !cookie.hostOnly ? 'TRUE' : 'FALSE';
            const path = cookie.path || '/';
            const secure = cookie.secure ? 'TRUE' : 'FALSE';
            const expires = cookie.expires === 'Infinity' || !cookie.expires ? 0 : Math.floor(new Date(cookie.expires as Date).getTime() / 1000);
            const name = cookie.key;
            const value = cookie.value;
            
            out += `${prefix}${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}\n`;
        }

        if (!this.source) return;

        if (this.source instanceof RawCookie) {
            await this.source.onWrite(out);
        } else if (typeof this.source === 'string') {
            fs.writeFileSync(this.source, out, 'utf8');
        }
    }

    getCookieString(url: string): string {
        return this.jar.getCookieStringSync(url);
    }
    
    setCookieString(cookieStr: string, url: string): void {
        try {
            this.jar.setCookieSync(cookieStr, url);
        } catch (e) {
        }
    }
}

export default CookieManager;
