import fs from 'node:fs';
import { CookieJar, Cookie } from 'tough-cookie';

export class RawCookie {
    constructor(
        public onRead: () => string | Promise<string>,
        public onWrite: (cookie: string) => void | Promise<void>
    ) {}
}

class CookieManager {
    private source: string | RawCookie | undefined;
    private loaded = false;
    public jar: CookieJar;

    constructor(source?: string | RawCookie) {
        this.source = source;
        this.jar = new CookieJar(undefined, { looseMode: true });
    }

    async load(): Promise<void> {
        if (!this.source) return;

        let content = '';
        try {
            if (this.source instanceof RawCookie) {
                content = await this.source.onRead();
            } else if (typeof this.source === 'string') {
                if (fs.existsSync(this.source)) {
                    content = fs.readFileSync(this.source, 'utf8');
                }
            }
        } catch (err) {
            // Best-effort: proceed without cookies rather than failing the whole request.
            console.warn('Failed to load cookies; continuing without them:', (err as Error).message);
            return;
        }
        this.loaded = true;

        if (!content) return;

        const lines = content.split('\n');
        for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed || (trimmed.startsWith('#') && !trimmed.startsWith('#HttpOnly_'))) continue;

            let isHttpOnly = false;
            let actualLine = trimmed;
            if (actualLine.startsWith('#HttpOnly_')) {
                isHttpOnly = true;
                actualLine = actualLine.substring(10);
            }

            const parts = actualLine.split('\t');
            if (parts.length < 7) continue;

            const domain = parts[0];
            const includesSubdomains = parts[1] === 'TRUE';
            const path = parts[2];
            const secure = parts[3] === 'TRUE';
            const expires = parseInt(parts[4]!, 10);
            const name = parts[5];
            const value = parts[6];

            try {
                const cookie = new Cookie({
                    key: name,
                    value: value,
                    domain: domain?.startsWith('.') ? domain.substring(1) : domain,
                    path: path,
                    secure: secure,
                    httpOnly: isHttpOnly,
                    hostOnly: !includesSubdomains,
                    expires: expires <= 0 ? 'Infinity' : new Date(expires * 1000)
                });

                const protocol = secure ? 'https' : 'http';
                const domainProp = cookie.domain || 'youtube.com';
                const host = domainProp.startsWith('.') ? domainProp.substring(1) : domainProp;
                const url = `${protocol}://${host}${path}`;

                this.jar.setCookieSync(cookie, url, { ignoreError: true });
            } catch (e) {
                // Skip malformed cookie lines
            }
        }
    }

    async save(): Promise<void> {
        if (!this.source) return;

        // Never overwrite the source with a partial jar: if the initial load failed
        // (e.g. a transient DB error), saving now would clobber the stored cookies.
        if (!this.loaded) {
            console.warn('Skipping cookie save because the initial cookie load failed');
            return;
        }

        try {
            let out = '# Netscape HTTP Cookie File\n';
            out += '# This file was generated by Node.js\n\n';

            const allCookies = await new Promise<Cookie[]>((resolve, reject) => {
                this.jar.store.getAllCookies((err, cookies) => {
                    if (err) reject(err);
                    else resolve(cookies || []);
                });
            });

            const seen = new Set<string>();
            for (const cookie of allCookies) {
                let prefix = cookie.httpOnly ? '#HttpOnly_' : '';
                let domain = cookie.domain || '';
                if (!cookie.hostOnly && !domain.startsWith('.')) domain = '.' + domain;
                const includeSubdomains = domain.startsWith('.') || !cookie.hostOnly ? 'TRUE' : 'FALSE';
                const path = cookie.path || '/';
                const secure = cookie.secure ? 'TRUE' : 'FALSE';
                const expires = cookie.expires === 'Infinity' || !cookie.expires ? 0 : Math.floor(new Date(cookie.expires as Date).getTime() / 1000);
                const name = cookie.key;
                const value = cookie.value;

                const dedupeKey = `${domain}\t${path}\t${name}`;
                if (seen.has(dedupeKey)) continue;
                seen.add(dedupeKey);

                out += `${prefix}${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}\n`;
            }

            if (this.source instanceof RawCookie) {
                await this.source.onWrite(out);
            } else if (typeof this.source === 'string') {
                fs.writeFileSync(this.source, out, 'utf8');
            }
        } catch (err) {
            // Persisting cookies is best-effort; never abort extraction because of it.
            console.warn('Failed to save cookies:', (err as Error).message);
        }
    }

    getCookieString(url: string): string {
        return this.jar.getCookieStringSync(url);
    }
    
    setCookieString(cookieStr: string, url: string): void {
        try {
            this.jar.setCookieSync(cookieStr, url);
        } catch (e) {
        }
    }
}

export default CookieManager;
