import fs from 'fs';
import { CookieJar, Cookie } from 'tough-cookie';

class CookieManager {
    private filePath: string;
    public jar: CookieJar;

    constructor(filePath: string) {
        this.filePath = filePath;
        this.jar = new CookieJar(undefined, { looseMode: true });
    }

    load(): void {
        if (!fs.existsSync(this.filePath)) return;
        
        const content = fs.readFileSync(this.filePath, 'utf8');
        const lines = content.split('\n');
        for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed || (trimmed.startsWith('#') && !trimmed.startsWith('#HttpOnly_'))) continue;
            
            let isHttpOnly = false;
            let actualLine = trimmed;
            if (actualLine.startsWith('#HttpOnly_')) {
                isHttpOnly = true;
                actualLine = actualLine.substring(10);
            }
            
            const parts = actualLine.split('\t');
            if (parts.length < 7) continue;
            
            const domain = parts[0];
            const includesSubdomains = parts[1] === 'TRUE';
            const path = parts[2];
            const secure = parts[3] === 'TRUE';
            const expires = parseInt(parts[4]!, 10);
            const name = parts[5];
            const value = parts[6];
            
            const cookie = new Cookie({
                key: name,
                value: value,
                domain: domain?.startsWith('.') ? domain.substring(1) : domain,
                path: path,
                secure: secure,
                httpOnly: isHttpOnly,
                hostOnly: !includesSubdomains,
                expires: expires <= 0 ? 'Infinity' : new Date(expires * 1000)
            });
            
            const protocol = secure ? 'https' : 'http';
            const domainProp = cookie.domain || 'youtube.com';
            const host = domainProp.startsWith('.') ? domainProp.substring(1) : domainProp;
            const url = `${protocol}://${host}${path}`;
            
            try {
                this.jar.setCookieSync(cookie, url, { ignoreError: true });
            } catch (e) {
            }
        }
    }

    save(): void {
        let out = '# Netscape HTTP Cookie File\n';
        out += '# This file was generated by Node.js\n\n';
        
        this.jar.store.getAllCookies((err: Error | null, allCookies?: Cookie[]) => {
            if (err) throw err;
            if (!allCookies) return;
            for (const cookie of allCookies) {
                let prefix = cookie.httpOnly ? '#HttpOnly_' : '';
                let domain = cookie.domain || '';
                if (!cookie.hostOnly && !domain.startsWith('.')) domain = '.' + domain;
                const includeSubdomains = domain.startsWith('.') || !cookie.hostOnly ? 'TRUE' : 'FALSE';
                const path = cookie.path || '/';
                const secure = cookie.secure ? 'TRUE' : 'FALSE';
                const expires = cookie.expires === 'Infinity' || !cookie.expires ? 0 : Math.floor(new Date(cookie.expires as Date).getTime() / 1000);
                const name = cookie.key;
                const value = cookie.value;
                
                out += `${prefix}${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}\n`;
            }
            fs.writeFileSync(this.filePath, out, 'utf8');
        });
    }

    getCookieString(url: string): string {
        return this.jar.getCookieStringSync(url);
    }
    
    setCookieString(cookieStr: string, url: string): void {
        try {
            this.jar.setCookieSync(cookieStr, url);
        } catch (e) {
        }
    }
}

export default CookieManager;
